# 网站配置 The Site Configuration

# 插入的主题 Import the theme
theme: jekyll-theme-chirpy

# 站点的语言 › http://www.lingoes.net/en/translator/langcode.htm
# 如果在文件夹 `_data/locales` 下存在同名文件，则布局语言也会改变，
# 否则，布局语言使用默认值 'en'。
lang: zh-CN

# 修改为你的时区 › https://kevinnovak.github.io/Time-Zone-Picker
timezone: Asia/Shanghai

# `jekyll-seo-tag` 设置开始 › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# ↓ --------------------------

title: RepoXu Blog # 网站主标题

tagline: 大傻春你想干什么 # 网站副标题

description: >- # 由 seo meta 和 atom feed 使用
  摸着石头过河，结果摸了一手屎

# 填入你的网站的协议和域名.
# 例如，'https://username.github.io'，注意不要以 '/' 结尾。
url: "https://repokx.github.io"

github:
  username: repokx # 更改为你的 github 用户名

twitter:
  username: repokx1 # 更改为你的 X（旧twitter）用户名

social:
  # 改为你的全名。
  # 这将会显示为帖子的默认作者以及页脚的“版权所有”者处
  name: Repo Xu
  email: repoexr@163.com # 更改为你的邮箱地址
  links:
    # 第一个链接将会作为默认作者的对应跳转链接。
    - https://space.bilibili.com/29035369
    - https://github.com/repokx # 更改为你的 github 主页链接
    - https://twitter.com/repokx1 # 更改为你的 twitter 主页链接
    # 取消注释以添加更多社交链接
    - https://www.facebook.com/repokx
    # - https://www.linkedin.com/in/username

# 网站认证设置 Site Verification Settings
webmaster_verifications:
  google: # 填入你的 google 认证代码
  bing: # 填入你的 bing 认证代码
  alexa: # 填入你的 alexa 认证代码
  yandex: # 填入你的 yandex 认证代码
  baidu: # 填入你的百度验证代码
  facebook: # 填入你的 facebook 验证代码

# ↑ --------------------------
# `jekyll-seo-tag` 设置结束

# 网页分析设置
analytics:
  google:
    id: G-3NE55EFMJV # 填入你的 Google Analytics ID
  goatcounter:
    id: # 填入你的 GoatCounter ID
  umami:
    id: # 填入你的 Umami ID
    domain: # 填入你的 Umami 域名
  matomo:
    id: # 填入你的 Matomo ID
    domain: # 填入你的 Matomo 域名
  cloudflare:
    id: # 填入你的 Cloudflare Web Analytics 令牌

# 页面浏览量设置
pageviews:
  provider: goatcounter # 当前只支持 'goatcounter'

# 设置首选配色方案
#
# 提示: 保留空白会跟随系统的默认首选配色，并且在侧边栏的底部会出现
# 一个可以转换亮色主题和暗色主题的按钮。
#
# 可用选项:
#
#     light  - 使用亮色方案
#     dark   - 使用暗色方案
#
theme_mode: # [light | dark]

# 媒体资源 CDN 端点。
# 注意，一旦被分配，CDN 网址会被加在
# 所有以 '/' 开始的媒体资源（网站头像，帖子中的图像，音频和视频文件）路径上
# 
# 例如，'https://cdn.com'
img_cdn:

# 侧边栏的头像，支持本地或 CROS 资源
avatar: "/assets/img/rioavat.png"

# SEO `og:image` 元标记中使用的全站社交预览图像的 URL。
# 可以在帖子的 Front Matter 中使用 `page.image` 覆盖。
social_preview_image:  # 字符串，本地或跨域资源

# 布尔类型，博文侧边栏目录的 `全局开关`
toc: true

comments:
  active: 'giscus' # 帖子评论区全局开关，例如，'disqus'。保持为空表示禁用。
  # 可用的选项如下：
  # disqus 评论系统
  disqus:
    shortname: # 填入你的 Disqus shortname. › https://help.disqus.com/en/articles/1717111-what-s-a-shortname
  # utterances 评论系统 › https://utteranc.es/
  utterances:
    repo: # <Github 用户名>/<仓库名>
    issue_term: # < 链接 | 路径 | 标题 | ...>
  # Giscus 选项 › https://giscus.app
  giscus:
    repo: repokx/repokx.github.io # <Github 用户名>/<仓库名>
    repo_id: R_kgDOOXZohg
    category: Announcements
    category_id: DIC_kwDOOXZohs4Co_zR
    mapping: pathname # 可选项，默认为 'pathname'
    input_position: Top # 可选项，默认为 'bottom'
    lang: zh-CN # 可选项，默认为 `site.lang` 的值
    reactions_enabled: # 可选项，默认为 1

# 自托管静态资产，可选 › https://github.com/cotes2020/chirpy-static-assets
assets:
  self_host:
    enabled: # 布尔值, 置空表示否
    # 指定 Jekyll 环境，置空意味着都启用
    # 仅在 `assets.self_host.enabled` 为 'true' 时生效
    env: # [development|production]

pwa:
  enabled: true # PWA 特性选项（可安装）
  cache:
    enabled: true # PWA 离线缓存选项
    # 在此处定义不被 PWA 缓存的路径。
    # 通常其值是使用和当前网站相同域名的其他网站的 `baseurl`。
    deny_paths:
      # - "/example"  # 符合 `<SITE_URL>/example/*` 的 URL 不会被 PWA 缓存

# 每一页的帖子数量
paginate: 24

# 网站的基础 URL
baseurl: ""

# ------------ 下面的设置不建议修改 ------------------

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge 设置 › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: "" # 空字符串意味着项目里的所有文件
      type: posts
    values:
      layout: post
      comments: true # 在帖子中启用评论
      toc: true # 在博文中显示 `目录栏目`
      # 不要改变它除非你是 Jekyll 以及 Web 开发的专家，
      # 或者你认为自己足够聪明可以在此模板中修改为其他的相对路径。
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs # 参考 `site.collections`
    values:
      layout: page
      permalink: /:title/
  - scope:
      path: assets/js/dist
    values:
      swcache: true

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - rollup.config.js
  - package*.json

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
